//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSJ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DSJTICKETEntities : DbContext
    {
        public DSJTICKETEntities()
            : base("name=DSJTICKETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblClasificacion> TblClasificacions { get; set; }
        public virtual DbSet<TblCuentaSucursale> TblCuentaSucursales { get; set; }
        public virtual DbSet<TblEmpresa> TblEmpresas { get; set; }
        public virtual DbSet<TblSucursale> TblSucursales { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TblAgente> TblAgentes { get; set; }
        public virtual DbSet<TblCoordinadore> TblCoordinadores { get; set; }
        public virtual DbSet<TblPersona> TblPersonas { get; set; }
        public virtual DbSet<Invenario> Invenarios { get; set; }
        public virtual DbSet<TblCuenta> TblCuentas { get; set; }
        public virtual DbSet<TblMenu> TblMenus { get; set; }
        public virtual DbSet<TblModulo> TblModulos { get; set; }
        public virtual DbSet<TblPermiso> TblPermisos { get; set; }
        public virtual DbSet<TblRol> TblRols { get; set; }
        public virtual DbSet<TblRolMenu> TblRolMenus { get; set; }
        public virtual DbSet<TblRolPermisoMenu> TblRolPermisoMenus { get; set; }
        public virtual DbSet<TblEstado> TblEstadoes { get; set; }
        public virtual DbSet<TblPrioridad> TblPrioridads { get; set; }
        public virtual DbSet<TblTicketDocumento> TblTicketDocumentoes { get; set; }
        public virtual DbSet<TblTicket> TblTickets { get; set; }
    }
}
