//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAgente
    {
        public int Id { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> CoordId { get; set; }
        public Nullable<int> IdModulo { get; set; }
        public string Profesion { get; set; }
        public string Cargo { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public byte[] FechaModificacion { get; set; }
    
        public virtual TblCoordinadore TblCoordinadore { get; set; }
        public virtual TblModulo TblModulo { get; set; }
    }
}
