//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCuenta()
        {
            this.TblCuentaSucursales = new HashSet<TblCuentaSucursale>();
            this.TblEmpresas = new HashSet<TblEmpresa>();
            this.TblPersonas = new HashSet<TblPersona>();
            this.TblTickets = new HashSet<TblTicket>();
            this.TblTickets1 = new HashSet<TblTicket>();
        }
    
        public int Id { get; set; }
        public string Correo { get; set; }
        public byte[] Clave { get; set; }

        public int idmodulo { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> IdRol { get; set; }
        public byte[] FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCuentaSucursale> TblCuentaSucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmpresa> TblEmpresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPersona> TblPersonas { get; set; }
        public virtual TblRol TblRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTicket> TblTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTicket> TblTickets1 { get; set; }
    }
}
