//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCuentaSucursale
    {
        public int Id { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public string Cargo { get; set; }
        public string Area { get; set; }
        public string CreadoPor { get; set; }
        public byte[] FechaCreacion { get; set; }
    
        public virtual TblCuenta TblCuenta { get; set; }
        public virtual TblSucursale TblSucursale { get; set; }
    }
}
