//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEstado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblEstado()
        {
            this.TblTickets = new HashSet<TblTicket>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Color { get; set; }
        public Nullable<int> Porcentaje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTicket> TblTickets { get; set; }
    }
}
