//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMenu()
        {
            this.TblRolMenus = new HashSet<TblRolMenu>();
            this.TblMenu1 = new HashSet<TblMenu>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Menu_padre_id { get; set; }
        public string Nombre { get; set; }
        public string Url { get; set; }
        public string Icono { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Accion { get; set; }
        public string Controlador { get; set; }
        public Nullable<int> IdModulo { get; set; }
        public string CreadoPor { get; set; }
        public byte[] FechaCreado { get; set; }
        public string Area { get; set; }
        public virtual TblModulo TblModulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblRolMenu> TblRolMenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMenu> TblMenu1 { get; set; }
        public virtual TblMenu TblMenu2 { get; set; }
    }
}
