//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRolMenu
    {
        public int Id { get; set; }
        public Nullable<int> IdRol { get; set; }
        public Nullable<int> IdMenu { get; set; }
        public byte[] FechaCreacion { get; set; }
    
        public virtual TblMenu TblMenu { get; set; }
        public virtual TblRol TblRol { get; set; }
    }
}
