//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRolPermisoMenu
    {
        public int Id { get; set; }
        public Nullable<int> IdMenu { get; set; }
        public string IdRol { get; set; }
        public string IdPermiso { get; set; }
        public Nullable<bool> activo { get; set; }
        public string CreadoPor { get; set; }
        public byte[] FechaCreado { get; set; }
    }
}
