//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTicket()
        {
            this.TblTicketDocumentoes = new HashSet<TblTicketDocumento>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdCuenta { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<System.TimeSpan> HoraApertura { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public Nullable<System.DateTime> FechaProceso { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<int> IdAgente { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdModulo { get; set; }
        public Nullable<int> IdPrioridad { get; set; }
        public Nullable<bool> EsEmpleado { get; set; }
        public byte[] FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual TblCuenta TblCuenta { get; set; }
        public virtual TblCuenta TblCuenta1 { get; set; }
        public virtual TblModulo TblModulo { get; set; }
        public virtual TblEstado TblEstado { get; set; }
        public virtual TblPrioridad TblPrioridad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTicketDocumento> TblTicketDocumentoes { get; set; }
    }
}
